=== GStudy2010/Dziennik/law/ksiegi/schematKsiegi.xsd
<?xml version="1.1" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Ksiega">
        <xs:complexType>
            <xs:choice>
                <xs:element name="EwidencjiDzieci" type="ksiegaEwidencjiDzieciTyp"/>
                <xs:element name="Uczniow" type="ksiegaUczniowTyp"/>
                <xs:element name="Sluchaczy" type="ksiegaSluchaczyTyp"/>
                <xs:element name="Wychowankow" type="ksiegaWychowankowTyp"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>


    <!-- definition of complex elements -->
    <xs:complexType name="ksiegaEwidencjiDzieciTyp">
        <xs:sequence>
            <xs:element name="NazwaPlacowki" type="xs:string"/>
            <xs:element name="AdresPlacowki" type="adresTyp"/>
            <xs:element name="Wojewodztwo" type="xs:string"/>
            <xs:element name="Gmina" type="xs:string"/>
            <xs:element name="DataZalozeniaEwidencji" type="xs:string"/>
            <xs:element name="Dzieci">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Dziecko" type="dzieckoTyp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ksiegaUczniowTyp">
        <xs:sequence>
            <xs:element name="NazwaPlacowki" type="xs:string"/>
            <xs:element name="AdresPlacowki" type="adresTyp"/>
            <xs:element name="Wojewodztwo" type="xs:string"/>
            <xs:element name="Gmina" type="xs:string"/>
            <xs:element name="DataZalozeniaEwidencji" type="xs:string"/>
            <xs:element name="Uczniowie">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Uczen" type="uczenTyp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ksiegaSluchaczyTyp">
        <xs:sequence>
            <xs:element name="NazwaPlacowki" type="xs:string"/>
            <xs:element name="AdresPlacowki" type="adresTyp"/>
            <xs:element name="Wojewodztwo" type="xs:string"/>
            <xs:element name="Gmina" type="xs:string"/>
            <xs:element name="DataZalozeniaEwidencji" type="xs:string"/>
            <xs:element name="Sluchacze">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Sluchacz" type="sluchaczTyp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ksiegaWychowankowTyp">
        <xs:sequence>
            <xs:element name="NazwaPlacowki" type="xs:string"/>
            <xs:element name="AdresPlacowki" type="adresTyp"/>
            <xs:element name="Wojewodztwo" type="xs:string"/>
            <xs:element name="Gmina" type="xs:string"/>
            <xs:element name="DataZalozeniaEwidencji" type="xs:string"/>
            <xs:element name="Wychowankowie">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Wychowanek" type="wychowanekTyp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="adresTyp">
        <xs:sequence>
            <xs:element name="KodPocztowy" type="xs:string"/>
            <xs:element name="Miejscowosc" type="xs:string"/>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="NumerDomu" type="xs:string"/>
            <xs:element name="NumerLokalu" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dzieckoTyp">
        <xs:sequence>
            <xs:element name="Numer" type="xs:integer" nillable="true" minOccurs="0"/>
            <xs:element name="Imie" type="xs:string"/>
            <xs:element name="DrugieImie" type="xs:string" minOccurs="0"/>
            <xs:element name="Nazwisko" type="xs:string"/>
            <xs:element name="DataUrodzenia" type="xs:date" minOccurs="0"/>
            <xs:element name="MiejsceUrodzenia" type="xs:string" minOccurs="0"/>
            <xs:element name="Pesel" type="xs:string" minOccurs="0"/>
            <xs:element name="NazwaINumerDokumentuPotwierdzajacegoTozsamosc" type="xs:string" minOccurs="0" />
            <xs:element name="Adres" type="adresTyp" minOccurs="0"/>
            <xs:element name="Rodzice" minOccurs="0">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Rodzic" type="rodzicTyp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="InformacjeOPrzedszkolu" type="xs:string" minOccurs="0"/>
            <xs:element name="InformacjeOOdroczeniu" type="xs:string" minOccurs="0"/>
            <xs:element name="InformacjeOSzkoleLubMiejscuRealizacjiZajecRewalidacyjnoWychowawczych" type="xs:string" minOccurs="0"/>
            <xs:element name="InformacjeOSpelnianiuPrzezDzieckoObowiazkuSzkolnegoPozaSzkola" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="uczenTyp">
        <xs:sequence>
            <xs:element name="Numer" type="xs:integer" nillable="true" minOccurs="0"/>
            <xs:element name="Imie" type="xs:string"/>
            <xs:element name="DrugieImie" type="xs:string" minOccurs="0"/>
            <xs:element name="Nazwisko" type="xs:string"/>
            <xs:element name="DataUrodzenia" type="xs:date" minOccurs="0"/>
            <xs:element name="MiejsceUrodzenia" type="xs:string" minOccurs="0"/>
            <xs:element name="Pesel" type="xs:string" minOccurs="0"/>
            <xs:element name="NazwaINumerDokumentuPotwierdzajacegoTozsamosc" type="xs:string" minOccurs="0"/>
            <xs:element name="Adres" type="adresTyp" minOccurs="0"/>
            <xs:element name="Rodzice" minOccurs="0">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Rodzic" type="rodzicTyp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DataRozpoczeciaNauki" type="xs:string" />
            <xs:element name="Oddzial" type="xs:string"/>
            <xs:element name="DataUkonczeniaSzkoly" type="xs:string" minOccurs="0"/>
            <xs:element name="DataIPrzyczynaOpuszczeniaSzkoly" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:assert test="not(DataIPrzyczynaOpuszczeniaSzkoly) or not(DataUkonczeniaSzkoly)"/>
    </xs:complexType>

    <xs:complexType name="sluchaczTyp">
        <xs:sequence>
            <xs:element name="Numer" type="xs:integer" nillable="true" minOccurs="0"/>
            <xs:element name="Imie" type="xs:string"/>
            <xs:element name="DrugieImie" type="xs:string" minOccurs="0"/>
            <xs:element name="Nazwisko" type="xs:string"/>
            <xs:element name="DataUrodzenia" type="xs:date" minOccurs="0"/>
            <xs:element name="MiejsceUrodzenia" type="xs:string" minOccurs="0"/>
            <xs:element name="Pesel" type="xs:string" minOccurs="0"/>
            <xs:element name="NazwaINumerDokumentuPotwierdzajacegoTozsamosc" type="xs:string" minOccurs="0"/>
            <xs:element name="Adres" type="adresTyp" minOccurs="0"/>
            <xs:element name="DataRozpoczeciaNauki" type="xs:string" />
            <xs:element name="Oddzial" type="xs:string"/>
            <xs:element name="DataUkonczeniaSzkoly" type="xs:string" minOccurs="0"/>
            <xs:element name="DataIPrzyczynaOpuszczeniaSzkoly" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:assert test="not(DataIPrzyczynaOpuszczeniaSzkoly) or not(DataUkonczeniaSzkoly)"/>
    </xs:complexType>

    <xs:complexType name="wychowanekTyp">
        <xs:sequence>
            <xs:element name="Numer" type="xs:integer" nillable="true" minOccurs="0"/>
            <xs:element name="Imie" type="xs:string"/>
            <xs:element name="DrugieImie" type="xs:string" minOccurs="0"/>
            <xs:element name="Nazwisko" type="xs:string"/>
            <xs:element name="DataUrodzenia" type="xs:date" minOccurs="0"/>
            <xs:element name="MiejsceUrodzenia" type="xs:string" minOccurs="0"/>
            <xs:element name="Pesel" type="xs:string" minOccurs="0"/>
            <xs:element name="NazwaINumerDokumentuPotwierdzajacegoTozsamosc" type="xs:string" minOccurs="0"/>
            <xs:element name="Adres" type="adresTyp" minOccurs="0"/>
            <xs:element name="Rodzice" minOccurs="0">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="Rodzic" type="rodzicTyp"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DataPrzyjeciaWychowankaDoPlacowki" type="xs:string" minOccurs="0"/>
            <xs:element name="DataSkresleniaZListyWychowankow" type="xs:string" minOccurs="0"/>
            <xs:element name="PrzyczynaSkresleniaZListyWychowankow" type="xs:string" minOccurs="0"/>
            <xs:element name="NazwaPlacowkiDoKtorejWychowanekZostalPrzeniesiony" type="xs:string" minOccurs="0"/>
            <xs:element name="AdresDoKtorejWychowanekZostalPrzeniesiony" type="adresTyp" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="rodzicTyp">
        <xs:sequence>
            <xs:element name="Imie" type="xs:string" minOccurs="0"/>
            <xs:element name="Nazwisko" type="xs:string" minOccurs="0"/>
            <xs:element name="Adres" type="adresTyp" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== GStudy2010/Dziennik/law/ksiegi/przyklady/ksiegaEwidencjiDzieci.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../schematEksportuDziennika.xsl"?>
<Ksiega
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../schematKsiegi.xsd">
    <EwidencjiDzieci>
    <NazwaPlacowki>Szkoła podstawowa numer 1</NazwaPlacowki>
    <AdresPlacowki>
        <KodPocztowy>01-123</KodPocztowy>
        <Miejscowosc>Warszawa</Miejscowosc>
        <Ulica>Ogrodowa</Ulica>
        <NumerDomu>1</NumerDomu>
        <NumerLokalu></NumerLokalu>
    </AdresPlacowki>
    <Wojewodztwo>mazowieckie</Wojewodztwo>
    <Gmina>Warszawa Wola</Gmina>
    <DataZalozeniaEwidencji>01.09.2020 r.</DataZalozeniaEwidencji>
    <Dzieci>
        <Dziecko id="1">
            <Numer>1</Numer>
            <Imie>Anna</Imie>
            <Nazwisko>Nowak</Nazwisko>
            <DataUrodzenia>2000-05-05</DataUrodzenia>
            <MiejsceUrodzenia>Gdańsk</MiejsceUrodzenia>
            <Pesel>001291019122</Pesel>
            <Adres>
                <KodPocztowy>00-123</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Aleje Jerozolimskie</Ulica>
                <NumerDomu>1</NumerDomu>
                <NumerLokalu>3</NumerLokalu>
            </Adres>
            <Rodzice>
                <Rodzic id="1">
                <Imie>Wiktor</Imie>
                <Nazwisko>Nowak</Nazwisko>
                <Adres>
                    <KodPocztowy>00-123</KodPocztowy>
                    <Miejscowosc>Warszawa</Miejscowosc>
                    <Ulica>Aleje Jerozolimskie</Ulica>
                    <NumerDomu>2</NumerDomu>
                    <NumerLokalu>4</NumerLokalu>
                </Adres>
                </Rodzic>
                <Rodzic id="2">
                    <Imie>Anna</Imie>
                    <Nazwisko>Nowak</Nazwisko>
                    <Adres>
                        <KodPocztowy>00-123</KodPocztowy>
                        <Miejscowosc>Warszawa</Miejscowosc>
                        <Ulica>Aleje Jerozolimskie</Ulica>
                        <NumerDomu>2</NumerDomu>
                        <NumerLokalu>4</NumerLokalu>
                    </Adres>
                </Rodzic>
            </Rodzice>
            <InformacjeOPrzedszkolu>Przedszkole nr 1</InformacjeOPrzedszkolu>
            <InformacjeOOdroczeniu>Informacje o odroczeniu</InformacjeOOdroczeniu>
            <InformacjeOSzkoleLubMiejscuRealizacjiZajecRewalidacyjnoWychowawczych>Informacje o szkole, w tym o szkole za granicą lub przy przedstawicielstwie dyplomatycznym innego państwa w Polsce</InformacjeOSzkoleLubMiejscuRealizacjiZajecRewalidacyjnoWychowawczych>
            <InformacjeOSpelnianiuPrzezDzieckoObowiazkuSzkolnegoPozaSzkola>Informacje o spełnianiu przez dziecko obowiązku szkolnego poza szkołą</InformacjeOSpelnianiuPrzezDzieckoObowiazkuSzkolnegoPozaSzkola>
        </Dziecko>
        <Dziecko id="2">
            <Numer>2</Numer>
            <Imie>Marian</Imie>
            <Nazwisko>Nowakowski</Nazwisko>
            <DataUrodzenia>2000-05-05</DataUrodzenia>
            <MiejsceUrodzenia>Warszawa</MiejsceUrodzenia>
            <NazwaINumerDokumentuPotwierdzajacegoTozsamosc>Dowód osobisty AZA 1234</NazwaINumerDokumentuPotwierdzajacegoTozsamosc>
            <Adres>
                <KodPocztowy>00-170</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Marszałkowska</Ulica>
                <NumerDomu>1</NumerDomu>
                <NumerLokalu>3</NumerLokalu>
            </Adres>
        </Dziecko>
    </Dzieci>
    </EwidencjiDzieci>
</Ksiega>

=== GStudy2010/Dziennik/law/ksiegi/przyklady/ksiegaSluchaczy.xml
<?xml version="1.1" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../schematEksportuDziennika.xsl"?>
<Ksiega
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../schematKsiegi.xsd">
    <Sluchaczy>
    <NazwaPlacowki>Szkoła policealna numer 1</NazwaPlacowki>
    <AdresPlacowki>
        <KodPocztowy>01-123</KodPocztowy>
        <Miejscowosc>Warszawa</Miejscowosc>
        <Ulica>Ogrodowa</Ulica>
        <NumerDomu>1</NumerDomu>
        <NumerLokalu></NumerLokalu>
    </AdresPlacowki>
    <Wojewodztwo>mazowieckie</Wojewodztwo>
    <Gmina>Warszawa Wola</Gmina>
    <DataZalozeniaEwidencji>01.09.2020 r.</DataZalozeniaEwidencji>
    <Sluchacze>
        <Sluchacz id="1">
            <Numer>1</Numer>
            <Imie>Anna</Imie>
            <Nazwisko>Nowak</Nazwisko>
            <DataUrodzenia>2000-05-05</DataUrodzenia>
            <MiejsceUrodzenia>Gdańsk</MiejsceUrodzenia>
            <Pesel>001291019122</Pesel>
            <Adres>
                <KodPocztowy>00-123</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Aleje Jerozolimskie</Ulica>
                <NumerDomu>1</NumerDomu>
                <NumerLokalu>3</NumerLokalu>
            </Adres>
            <DataRozpoczeciaNauki>01.09.2020 r.</DataRozpoczeciaNauki>
            <Oddzial>1A</Oddzial>
            <DataIPrzyczynaOpuszczeniaSzkoly>12.12.2020 r. Przeprowadzka</DataIPrzyczynaOpuszczeniaSzkoly>
        </Sluchacz>
        <Sluchacz id="2">
            <Numer>2</Numer>
            <Imie>Marian</Imie>
            <Nazwisko>Nowakowski</Nazwisko>
            <DataUrodzenia>2000-05-05</DataUrodzenia>
            <MiejsceUrodzenia>Warszawa</MiejsceUrodzenia>
            <NazwaINumerDokumentuPotwierdzajacegoTozsamosc>Dowód osobisty AZA 1234</NazwaINumerDokumentuPotwierdzajacegoTozsamosc>
            <Adres>
                <KodPocztowy>00-170</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Marszałkowska</Ulica>
                <NumerDomu>1</NumerDomu>
                <NumerLokalu>3</NumerLokalu>
            </Adres>
            <DataRozpoczeciaNauki>01.09.2019 r.</DataRozpoczeciaNauki>
            <Oddzial>1B</Oddzial>
            <DataUkonczeniaSzkoly>26.06.2020 r.</DataUkonczeniaSzkoly>
        </Sluchacz>
    </Sluchacze>
    </Sluchaczy>
</Ksiega>

=== GStudy2010/Dziennik/law/ksiegi/przyklady/ksiegaUczniow.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../schematEksportuDziennika.xsl"?>
<Ksiega
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../schematKsiegi.xsd">
    <Uczniow>
    <NazwaPlacowki>Szkoła podstawowa numer 1</NazwaPlacowki>
    <AdresPlacowki>
        <KodPocztowy>01-123</KodPocztowy>
        <Miejscowosc>Warszawa</Miejscowosc>
        <Ulica>Ogrodowa</Ulica>
        <NumerDomu>1</NumerDomu>
        <NumerLokalu></NumerLokalu>
    </AdresPlacowki>
    <Wojewodztwo>mazowieckie</Wojewodztwo>
    <Gmina>Warszawa Wola</Gmina>
    <DataZalozeniaEwidencji>01.09.2020 r.</DataZalozeniaEwidencji>
    <Uczniowie>
        <Uczen id="1">
            <Numer>1</Numer>
            <Imie>Anna</Imie>
            <Nazwisko>Nowak</Nazwisko>
            <DataUrodzenia>2013-05-05</DataUrodzenia>
            <MiejsceUrodzenia>Gdańsk</MiejsceUrodzenia>
            <Pesel>001291019122</Pesel>
            <Adres>
                <KodPocztowy>00-123</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Aleje Jerozolimskie</Ulica>
                <NumerDomu>1</NumerDomu>
                <NumerLokalu>3</NumerLokalu>
            </Adres>
            <Rodzice>
                <Rodzic id="1">
                <Imie>Wiktor</Imie>
                <Nazwisko>Nowak</Nazwisko>
                <Adres>
                    <KodPocztowy>00-123</KodPocztowy>
                    <Miejscowosc>Warszawa</Miejscowosc>
                    <Ulica>Aleje Jerozolimskie</Ulica>
                    <NumerDomu>2</NumerDomu>
                    <NumerLokalu>4</NumerLokalu>
                </Adres>
                </Rodzic>
                <Rodzic id="2">
                    <Imie>Anna</Imie>
                    <Nazwisko>Nowak</Nazwisko>
                    <Adres>
                        <KodPocztowy>00-123</KodPocztowy>
                        <Miejscowosc>Warszawa</Miejscowosc>
                        <Ulica>Aleje Jerozolimskie</Ulica>
                        <NumerDomu>2</NumerDomu>
                        <NumerLokalu>4</NumerLokalu>
                    </Adres>
                </Rodzic>
            </Rodzice>
            <DataRozpoczeciaNauki>01.09.2020 r.</DataRozpoczeciaNauki>
            <Oddzial>1A</Oddzial>
        </Uczen>
        <Uczen id="2">
            <Numer>2</Numer>
            <Imie>Marian</Imie>
            <Nazwisko>Nowakowski</Nazwisko>
            <DataUrodzenia>2013-08-14</DataUrodzenia>
            <MiejsceUrodzenia>Warszawa</MiejsceUrodzenia>
            <NazwaINumerDokumentuPotwierdzajacegoTozsamosc>Dowód osobisty AZA 1234</NazwaINumerDokumentuPotwierdzajacegoTozsamosc>
            <Adres>
                <KodPocztowy>00-170</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Marszałkowska</Ulica>
                <NumerDomu>1</NumerDomu>
                <NumerLokalu>3</NumerLokalu>
            </Adres>
            <DataRozpoczeciaNauki>01.09.2019 r.</DataRozpoczeciaNauki>
            <Oddzial>1B</Oddzial>
            <DataIPrzyczynaOpuszczeniaSzkoly>30.06.2021 r. Przeprowadzka</DataIPrzyczynaOpuszczeniaSzkoly>
        </Uczen>
    </Uczniowie>
    </Uczniow>
</Ksiega>

=== GStudy2010/Dziennik/law/ksiegi/przyklady/ksiegaWychowankow.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../schematEksportuDziennika.xsl"?>
<Ksiega
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../schematKsiegi.xsd">
    <Wychowankow>
    <NazwaPlacowki>Młodzieżowy Ośrodek Wychowawczy numer 1</NazwaPlacowki>
    <AdresPlacowki>
        <KodPocztowy>01-123</KodPocztowy>
        <Miejscowosc>Warszawa</Miejscowosc>
        <Ulica>Ogrodowa</Ulica>
        <NumerDomu>1</NumerDomu>
        <NumerLokalu></NumerLokalu>
    </AdresPlacowki>
    <Wojewodztwo>mazowieckie</Wojewodztwo>
    <Gmina>Warszawa Wola</Gmina>
    <DataZalozeniaEwidencji>01.09.2020 r.</DataZalozeniaEwidencji>
    <Wychowankowie>
        <Wychowanek id="1">
            <Numer>1</Numer>
            <Imie>Anna</Imie>
            <Nazwisko>Nowak</Nazwisko>
            <DataUrodzenia>2000-05-05</DataUrodzenia>
            <MiejsceUrodzenia>Gdańsk</MiejsceUrodzenia>
            <Pesel>001291019122</Pesel>
            <Adres>
                <KodPocztowy>00-123</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Aleje Jerozolimskie</Ulica>
                <NumerDomu>1</NumerDomu>
                <NumerLokalu>3</NumerLokalu>
            </Adres>
            <Rodzice>
                <Rodzic id="1">
                <Imie>Wiktor</Imie>
                <Nazwisko>Nowak</Nazwisko>
                <Adres>
                    <KodPocztowy>00-123</KodPocztowy>
                    <Miejscowosc>Warszawa</Miejscowosc>
                    <Ulica>Aleje Jerozolimskie</Ulica>
                    <NumerDomu>2</NumerDomu>
                    <NumerLokalu>4</NumerLokalu>
                </Adres>
                </Rodzic>
                <Rodzic id="2">
                    <Imie>Anna</Imie>
                    <Nazwisko>Nowak</Nazwisko>
                    <Adres>
                        <KodPocztowy>00-123</KodPocztowy>
                        <Miejscowosc>Warszawa</Miejscowosc>
                        <Ulica>Aleje Jerozolimskie</Ulica>
                        <NumerDomu>2</NumerDomu>
                        <NumerLokalu>4</NumerLokalu>
                    </Adres>
                </Rodzic>
            </Rodzice>
            <DataPrzyjeciaWychowankaDoPlacowki>01.12.2014 r.</DataPrzyjeciaWychowankaDoPlacowki>
            <DataSkresleniaZListyWychowankow>10.09.2019 r.</DataSkresleniaZListyWychowankow>
            <PrzyczynaSkresleniaZListyWychowankow>Przeprowadzka</PrzyczynaSkresleniaZListyWychowankow>
            <NazwaPlacowkiDoKtorejWychowanekZostalPrzeniesiony>Młodzieżowy Ośrodek Wychowawczy numer 2 w Warszawie</NazwaPlacowkiDoKtorejWychowanekZostalPrzeniesiony>
            <AdresDoKtorejWychowanekZostalPrzeniesiony>
                <KodPocztowy>01-213</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Nowogrodzka</Ulica>
                <NumerDomu>12</NumerDomu>
                <NumerLokalu></NumerLokalu>
            </AdresDoKtorejWychowanekZostalPrzeniesiony>
        </Wychowanek>
        <Wychowanek id="2">
            <Numer>2</Numer>
            <Imie>Marian</Imie>
            <Nazwisko>Nowakowski</Nazwisko>
            <DataUrodzenia>2000-05-05</DataUrodzenia>
            <MiejsceUrodzenia>Warszawa</MiejsceUrodzenia>
            <NazwaINumerDokumentuPotwierdzajacegoTozsamosc>Dowód osobisty AZA 1234</NazwaINumerDokumentuPotwierdzajacegoTozsamosc>
            <Adres>
                <KodPocztowy>00-170</KodPocztowy>
                <Miejscowosc>Warszawa</Miejscowosc>
                <Ulica>Marszałkowska</Ulica>
                <NumerDomu>1</NumerDomu>
                <NumerLokalu>3</NumerLokalu>
            </Adres>
            <DataPrzyjeciaWychowankaDoPlacowki>10.12.2016 r.</DataPrzyjeciaWychowankaDoPlacowki>
        </Wychowanek>
    </Wychowankowie>
    </Wychowankow>
</Ksiega>
